export const MAX_DEPTH_RANGE_MIN = 0
export const MAX_DEPTH_RANGE_MAX = 5
export const MAX_DEPTH_DEFAULT = 2

export const MAX_DIST_RANGE_MIN = 0
export const MAX_DIST_RANGE_MAX = 5
export const MAX_DIST_DEFALT = 2


export default {
  MAX_DEPTH_RANGE_MIN,
  MAX_DEPTH_RANGE_MAX,
  MAX_DEPTH_DEFAULT,
  MAX_DIST_RANGE_MIN,
  MAX_DIST_RANGE_MAX,
  MAX_DIST_DEFALT
}
