export const CSRF_TOKEN_HEADER = 'X-CSRFToken'
export const FLOW_CLASS = 'flowtype'

export const APP_PREFIX = 'ANCHOR'

export const ROUTER_REALM = 'anchor'
export const TOPIC_COVER_STARTED = 'TOPIC_COVER_STARTED'
export const TOPIC_COVER_FINISHED = 'TOPIC_COVER_FINISHED'

export const LOCAL_STORAGE_SESSION_KEY = `${APP_PREFIX}_SESSION_KEY`
export const LOCAL_STORAGE_CSRF_KEY = `${APP_PREFIX}_CSRF`

export const SIGNUP_STEP_USER = 'SIGNUP_STEP_USER'
export const SIGNUP_STEP_PASSWORD = 'SIGNUP_STEP_PASSWORD'

export const DASH_BOARD_GENERAL_SETTINGS = 'DASH_BOARD_GENERAL_SETTINGS'
export const DASH_BOARD_ADVANCED_SETTINGS = 'DASH_BOARD_ADVANCED_SETTINGS'

export default {
  CSRF_TOKEN_HEADER,
  FLOW_CLASS,
  APP_PREFIX,
  ROUTER_REALM,
  TOPIC_COVER_STARTED,
  TOPIC_COVER_FINISHED,
  LOCAL_STORAGE_SESSION_KEY,
  LOCAL_STORAGE_CSRF_KEY,
  SIGNUP_STEP_USER,
  SIGNUP_STEP_PASSWORD,
  DASH_BOARD_GENERAL_SETTINGS,
  DASH_BOARD_ADVANCED_SETTINGS,
}
