export const CSRF_TOKEN_HEADER = 'X-CSRFToken'
export const FLOW_CLASS = 'flowtype'

export const APP_PREFIX = 'ANCHOR'
export const LOCAL_STORAGE_SESSION_KEY = `${APP_PREFIX}_SESSION_KEY`
export const LOCAL_STORAGE_CSRF_KEY = `${APP_PREFIX}_CSRF`

export const SIGNUP_STEP_USER = 'SIGNUP_STEP_USER'
export const SIGNUP_STEP_PASSWORD = 'SIGNUP_STEP_PASSWORD'

export const SETTINGS_BASIC = 'SETTINGS_BASIC'
export const SETTINGS_ADVANCED = 'SETTINGS_ADVANCED'

export default {
  CSRF_TOKEN_HEADER,
  FLOW_CLASS,
  APP_PREFIX,
  LOCAL_STORAGE_SESSION_KEY,
  LOCAL_STORAGE_CSRF_KEY,
  SIGNUP_STEP_USER,
  SIGNUP_STEP_PASSWORD,
  SETTINGS_BASIC,
  SETTINGS_ADVANCED,
}
